name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') --disable=import-error,relative-beyond-top-level,missing-module-docstring,missing-class-docstring,missing-function-docstring,line-too-long,broad-exception-caught,no-else-break,no-else-return,unused-argument,ungrouped-imports,consider-using-f-string,wrong-import-position